# -*- coding: utf-8 -*-
"""Chapter1_Challenge_AlifEriksandiAgustino.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ByJGoKtzxlmBWUBZuRSLR7apmi2OWEP0

# GDGoC ML Study Jam - Chapter 1 Challenge
## **Topic: The Smartphone Analyst**

Selamat datang, Data Detective! 🕵️‍♂️

Hari ini, kita tidak hanya belajar koding, tapi belajar **memecahkan masalah menggunakan data**.

**Skenario:**
Kamu adalah Lead Data Analyst di sebuah toko gadget besar. Bosmu memberikan dataset spesifikasi smartphone dan memintamu menjawab **10 Pertanyaan Bisnis** untuk strategi penjualan bulan depan.

**Aturan Main:**
1.  **Bebas Berkreasi:** Gunakan metode apapun (Filtering, Sorting, Grouping, atau Visualisasi Grafik).
2.  **Wajib Ada Insight:** Setelah kode dijalankan, tulis kesimpulanmu di cell Teks di bawahnya.
3.  **Have Fun!**
"""

# ⚠️ JALANKAN CELL INI TERLEBIH DAHULU!
# Script ini akan membuat dataset dummy untuk latihan kita hari ini.

import pandas as pd
import numpy as np
import random

np.random.seed(42)

# Data Dummy
n_data = 150
brands = ['Samsung', 'Apple', 'Xiaomi', 'Oppo', 'Vivo', 'Realme', 'Infinix', 'Asus', 'Google']
rams = [4, 6, 8, 12, 16, 24] # Ada RAM 24GB buat gaming
storages = [64, 128, 256, 512, 1024]

data = {
    'Brand': [random.choice(brands) for _ in range(n_data)],
    'Model': [f"Phone {i}" for i in range(n_data)],
    'RAM_GB': [random.choice(rams) for _ in range(n_data)],
    'Storage_GB': [random.choice(storages) for _ in range(n_data)],
    'Rating': [round(random.uniform(3.0, 5.0), 1) for _ in range(n_data)]
}

df = pd.DataFrame(data)

# Bikin harga agak logis -> (RAM gede + Storage gede = Mahal) + sedikit random noise
df['Price_Juta'] = (df['RAM_GB'] * 0.5) + (df['Storage_GB'] * 0.015) + np.random.randint(1, 4, n_data)
df['Price_Juta'] = df['Price_Juta'].round(1)

# Tambahin Data -> "Aneh" (Anomaly)
df.loc[148] = ['Nokia', 'Nokia 3310 Reborn', 2, 16, 50.0, 5.0] # HP kentang harga sultan
df.loc[149] = ['Unknown', 'Prototype X', 128, 2048, 0.5, 1.0] # Spek dewa harga permen

print("Dataset 'smartphones' berhasil dibuat!")
print(f"Total Data: {len(df)} baris.")
df.head(10)

"""---
### **Quest 1: Cek Ombak (Overview)**
Sebelum masuk ke analisis dalam, coba cek dulu isi gudang kita.
1. Ada berapa baris dan kolom di data ini?
2. Apa saja nama kolomnya?
3. Tampilkan statistik dasarnya (Rata-rata, Max, Min).

*Hint: Gunakan `.shape`, `.columns`, dan `.describe()`.*
"""

# 1. Ada berapa baris dan kolom di data ini?
print("1. Baris dan Kolom")
print(f"Jumlah Baris: {df.shape[0]}")
print(f"Jumlah Kolom: {df.shape[1]}")

# 2. Apa saja nama kolomnya?
print("\n2. Nama Kolom")
print(df.columns.tolist())

# 3. Tampilkan statistik dasarnya (Rata-rata, Max, Min).
print("\n3. Statistik Dasar")
print(df.describe())

"""Dari hasil df.describe(), terlihat ada anomali pada data. Rata-rata rating terlihat normal, namun nilai Max Rating mencapai 50.0, padahal seharusnya skala rating hanya sampai 5.0. Selain itu, ada smartphone dengan RAM 128 GB yang jauh di atas rata-rata pasar. Ini mengindikasikan adanya data outliers yang perlu dibersihkan nanti.

---
### **Quest 2: Raja Pasar**
Brand apa yang paling banyak memiliki model HP dalam daftar ini?

*Hint: Gunakan `.value_counts()`.*
"""

# Menghitung jumlah kemunculan setiap Brand
jumlah_per_brand = df['Brand'].value_counts()

print("Peringkat Brand")
print(jumlah_per_brand)

# Paling banyak model hp
model_terbanyak = jumlah_per_brand.idxmax()
jumlahnya = jumlah_per_brand.max()

print(f"\nPaling banyak adalah: {model_terbanyak} dengan total {jumlahnya} model.")

"""Berdasarkan hasil analisis menggunakan .value_counts(), Xiaomi adalah brand yang paling mendominasi dataset dengan total 22 model. Sementara itu, brand Nokia memiliki jumlah model paling sedikit.

---
### **Quest 3: Storage Wars**
Zaman sekarang aplikasi makin besar.
Coba cari HP yang punya **Storage paling besar** (Max Storage). Ada berapa HP yang punya storage segitu?

*Hint: Cari nilai max dulu, lalu filter datanya.*
"""

# 1. Storage paling besar (Max)
max_storage = df['Storage_GB'].max()
print(f"Kapasitas Storage Terbesar: {max_storage} GB")

# 2. Filter data: HP yang punya storage sebesar max_storage
hp_storage_besar = df[df['Storage_GB'] == max_storage]

# 3. Tampilkan hasil
print(f"Jumlah HP dengan storage besar: {len(hp_storage_besar)} unit")
print("\nDetail HP:")
hp_storage_besar # Menampilkan tabel baris yang lolos filter

"""Ditemukan bahwa kapasitas storage terbesar dalam dataset adalah 2048 GB (2 TB). Hanya ada 1 unit HP yang memiliki storage sebesar ini, yaitu Brand Unknown dengan model Prototype X. Ini merupakan data anomali karena jauh di atas standar pasar HP saat ini, dan brand-nya pun tidak dikenal.

---
### **Quest 4: Budget vs Premium**
Bos ingin tahu rentang harga pasar.
1. Berapa harga HP **termurah**?
2. Berapa harga HP **termahal**?

*Hint: Gunakan `.min()` dan `.max()` pada kolom harga.*
"""

# Cari harga termurah dan termahal
harga_min = df['Price_Juta'].min()
harga_max = df['Price_Juta'].max()

print(f"Harga Termurah: {harga_min} Juta")
print(f"Harga Termahal: {harga_max} Juta")

print("\nDetail HP Termurah")
print(df[df['Price_Juta'] == harga_min][['Brand', 'Model', 'RAM_GB', 'Price_Juta']])

print("\nDetail HP Termahal")
print(df[df['Price_Juta'] == harga_max][['Brand', 'Model', 'RAM_GB', 'Price_Juta']])

"""Harga termurah adalah 1.0 Juta, namun ini dimiliki oleh 'Prototype X' yang memiliki RAM 128GB. Sedangkan harga termahal mencapai sekitar 30-an Juta.

---
### **Quest 5: The Gaming Beast**
Seorang Gamer datang mencari HP. Syaratnya mutlak:
1. **RAM wajib di atas 12 GB.**
2. **Storage minimal 512 GB.**

Tampilkan daftar HP yang memenuhi syarat tersebut!

*Hint: Gunakan Filtering dengan logika AND (`&`).*
"""

hp_gaming = df[(df['RAM_GB'] > 12) & (df['Storage_GB'] >= 512)]

print(f"Ada {len(hp_gaming)} HP Gaming")
print("\nDaftar HP Gaming")
hp_gaming

"""Dari hasil filtering, ada 26 model HP dengan spesifikasi gaming (RAM 16GB ke atas dan Storage besar) dari brand yang berbeda-beda.

---
### **Quest 6: Sobat Mahasiswa**
Mahasiswa biasanya cari HP yang "Worth it".
Cari HP yang harganya **di bawah 7 Juta**, TAPI **Rating-nya di atas 4.5**.

Ada nggak barangnya?
"""

# Filter data: Harga < 7 Juta DAN Rating > 4.5
hp_mahasiswa = df[(df['Price_Juta'] < 7) & (df['Rating'] > 4.5)]

print(f"Ditemukan {len(hp_mahasiswa)} HP yang cocok untuk mahasiswa")
print("\nDaftar HP Worth It")
hp_mahasiswa

"""Setelah difilter, ada 7 model HP yang cocok untuk mahasiswa dari 5 brand hp yang berbeda

---
### **Quest 7: Fanboy Apple**
Ada pelanggan yang cuma mau beli **Apple**.
Tampilkan semua HP merk Apple, lalu urutkan dari yang **paling mahal ke paling murah**.

*Hint: Filter `Brand == 'Apple'`, lalu `sort_values`.*
"""

# 1. Filter: Brand Apple
apple_only = df[df['Brand'] == 'Apple']

# 2. Sort: Urutkan Besar ke Kecil
apple_sorted = apple_only.sort_values(by='Price_Juta', ascending=False)

print(f"Ditemukan {len(apple_sorted)} model Apple.")
print("\nKatalog Apple (Termahal ke Termurah)")
apple_sorted

"""Berdasarkan data yang difilter, varian HP Apple termahal di toko harganya 22.4 Juta. Sedangkan varian termurahnya ada di angka 4.0 Juta. Dengan mengurutkan seperti ini, kita bisa langsung menawarkan opsi terbaik saat pelanggan Apple Fanboy datang menanyakan model terbaik.

---
### **Quest 8: Rata-Rata Harga per Brand (Level Medium)**
Brand mana yang rata-rata harga produknya paling mahal?
Coba hitung rata-rata harga (`Price_Juta`) untuk setiap `Brand`.

*Hint: Ini butuh Grouping. Gunakan `.groupby('Brand')['Price_Juta'].mean()`.*
"""

# 1. Grouping
rata_rata_harga = df.groupby('Brand')['Price_Juta'].mean()

# 2. Sorting: Urutkan dari rata-rata termahal ke termurah
rata_rata_sorted = rata_rata_harga.sort_values(ascending=False)

print("Rata-Rata Harga HP per Brand (Juta)")
print(rata_rata_sorted)

print(f"\nBrand dengan harga rata rata HP tertinggi adalah {rata_rata_sorted.idxmax()}")

"""Berdasarkan rata-rata harga, brand Asus menempati posisi pertama sebagai brand paling mahal/premium, dengan rata-rata harga sekitar 19 Juta. Hal ini menunjukkan bahwa stok Asus didominasi oleh varian spesifikasi tinggi. Sebaliknya, brand Nokia dan Unknown memiliki rata-rata harga terendah, cocok untuk target pasar entry-level.

---
### **Quest 9: Value for Money (Feature Engineering)**
Kita mau cari HP yang "Spek Dewa Harga Kaki Lima".
1. Buat kolom baru bernama `Skor_Performa` = `RAM_GB` + `Storage_GB`.
2. Buat kolom baru bernama `Value_Skor` = `Skor_Performa` / `Price_Juta`.
3. Tampilkan 5 HP dengan `Value_Skor` tertinggi.

*Hint: Kamu bisa melakukan operasi matematika antar kolom secara langsung.*
"""

# 1. Buat kolom 'Skor_Performa' (RAM + Storage)
df['Skor_Performa'] = df['RAM_GB'] + df['Storage_GB']

# 2. Buat kolom 'Value_Skor' (Performa banding Harga)
df['Value_Skor'] = df['Skor_Performa'] / df['Price_Juta']

# 3. Urutkan dan Tampilkan 5 terbaik
top_value = df.sort_values(by='Value_Skor', ascending=False).head(5)

print("Top 5 HP dengan value terbaik")
print(top_value[['Brand', 'Model', 'RAM_GB', 'Storage_GB', 'Price_Juta', 'Value_Skor']])

"""Setelah menghitung Value_Skor, peringkat 1 ditempati oleh 'Prototype X'. Ini terjadi karena dia memiliki Storage sangat besar (2048 GB) tapi harganya sangat murah. Skornya menjadi sangat tinggi secara tidak wajar. Di tempat ke 2 ada brand HP dari Apple yang menawarkan storage besar dengan harga kompetitif.

---
### **Quest 10: The Detective (Final Boss)**
Ada laporan data error di sistem.
1. Cari HP yang harganya **di atas 40 Juta** (Kemahalan/Mustahil).
2. Cari HP yang harganya **di bawah atau sama dengan 1 Juta** tapi RAM-nya **di atas 100 GB** (Ngawur).

Temukan data penyusup ini!

*Hint: Gunakan filtering untuk mencari outlier.*
"""

# 1: Harga di atas 40 Juta
error_1 = df['Price_Juta'] > 40

# 2: Harga <= 1 Juta dan RAM > 100 GB
error_2 = (df['Price_Juta'] <= 1) & (df['RAM_GB'] > 100)

data_error = df[error_1 | error_2]

print("LAPORAN ERROR DITEMUKAN")
print(f"Jumlah Data Error: {len(data_error)}")
data_error

"""# 🎉 Mission Accomplished!

Selamat! Kamu sudah menyelesaikan 10 Misi.
Jangan lupa:
1.  **Kumpulkan di Google Classroom**
2.  Kumpulkan dalam bentuk link colab (Can Edit Access).

Sampai jumpa di Chapter 2!
"""